###########################################
# GENERAL SETTINGS #####################
###########################################
general:
  # whether to use paths_debug or paths
  debug: False
  # whether to write a log file to disk
  logging_to_disk: True
  # number of gpus to use
  number_of_gpus: 4
  # number of cpus used for image pre-processing (use all if possible)
  number_of_cpus: 32
  # number of images buffered in image pre-processing
  # (reduce if memory problems)
  buffer_size: 32768
  # Batch size used in model training (number of images per update)
  # batch is is split to all GPUs - has to be divisible by number of GPUs
  # Use values in (16, 32, 64, 128, 256, 512)
  batch_size: 128
  # max number of training epochs after which training is stopped
  max_number_of_epochs: 70

###########################################
# RUN CONFIG #####################
###########################################

run:
  # choose location for current run
  location: west_africa
  # choose experiment for current run
  experiment: species
  # add a postfix to the run_YYYYMMDDHH run directory
  identifier_postfix: ''

###########################################
# PATHS #####################
###########################################

paths:
  # root path of the project containing all data and directory structure
  root: '/host/data_hdd/'
  # experiments directory (relative to root)
  experiments: 'experiments/'
  # models directory (relative to root)
  models: 'models/'

# Paths used in debug mode (local machine)
paths_debug:
  root: 'D:\\Studium_GD\\Zooniverse\\Data\\camtrap_trainer\\data\\'
  experiments: 'experiments\\'
  models: 'models\\'

###########################################
# AVAILABLE MODELS ########################
###########################################

models:
  # Model name
  ResNet18:
    image_processing:
      # image output size of pre-processing (input to training)
      output_height: 224
      output_width: 224
      # resizing options for data augmentation
      resize_side_min: 224
      resize_side_max: 246
      # whether to use color data augmentation (randomly adjust colors)
      color_manipulations: True
  ResNet34:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  ResNet50:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  ResNet101:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  ResNet152:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  InceptionResNetV2:
    image_processing:
      output_height: 299
      output_width: 299
      resize_side_min: 299
      resize_side_max: 329
      color_manipulations: True
  cats_vs_dogs:
    image_processing:
      output_height: 150
      output_width: 150
      resize_side_min: 150
      resize_side_max: 165
      color_manipulations: True


locations:
  ###########################################
  # DEFAULT CONFIG ########################
  # (used if not overriden)
  ###########################################
  # location name
  default_config:
    # max image save side when creating tfrecord files and
    # aspect preserving resizing
    # (must be larger than input to models, too large can degrade performance)
    image_save_side_max: 500
    # Training split sizes - name and size
    # train, validation and test cannot be renamed and must exist
    training_splits:
      train: 0.9
      validation: 0.05
      test: 0.05
    # all experiments of dat location
    experiments:
      # experiment name
      default_config:
        # model name
        model: ResNet18
        # whether to balance classes by sampling to frequency of Least
        # frequent class
        balanced_sampling_min: False
        # label type to use for balanced sampling
        balanced_sampling_label_type: 'primary'
        # Options to load a pre-trained model from disk
        load_model_from_disk:
          # continue training from a model on disk
          continue_training: False
          # use transfer learning (i.e. randomly initialize last layer)
          transfer_learning: False
          # directory of model to load (relative to root)
          model_dir_to_load: ''
          # name of model file to load (incl. extension)
          model_file_to_load: ''
  ###########################################
  # SOUTHERN AFRICA ########################
  ###########################################
  southern_africa:
    paths:
      master_tfr: 'master.tfrecord'
      inventory: 'inventory_list.csv'
    experiments:
      empty_vehicle_species:
        model: ResNet18
        label_types_to_model:
          - 'species'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'species'
      species:
        model: InceptionResNetV2
        label_types_to_model:
          - 'species'
        load_model_from_disk:
          continue_training: True
          transfer_learning: False
          model_dir_to_load: 'southern_africa/experiments/species/run_201804032004_incresv2'
          model_file_to_load: 'latest'
  ###########################################
  # WEST AFRICA ########################
  ###########################################
  west_africa:
    paths:
      master_tfr: 'master.tfrecord'
      inventory: 'inventory_list.csv'
    experiments:
      empty_species:
        model: InceptionResNetV2
        label_types_to_model:
          - 'species'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'species'
      species:
        model: InceptionResNetV2
        label_types_to_model:
          - 'species'
        load_model_from_disk:
          continue_training: True
          transfer_learning: False
          model_dir_to_load: 'west_africa/experiments/species/run_201805180005'
          model_file_to_load: 'latest'
  ###########################################
  # CATS AND DOGS (TESTING) ################
  ###########################################
  cats_and_dogs:
    image_save_side_max: 200
    paths:
      master_tfr: 'master.tfrecord'
      inventory: 'inventory_list.csv'
      images: "D:\\Studium_GD\\Zooniverse\\Data\\transfer_learning_project\\images\\4715\\all"
    experiments:
      cats_vs_dogs:
        model: cats_vs_dogs
        load_model_from_disk:
          continue_training: False
          transfer_learning: True
          #model_dir_to_load: 'southern_africa\\experiments\\species\\models'
          model_dir_to_load: 'cats_and_dogs\\experiments\\cats_vs_dogs\\run_201804041504_model_loading'
          model_file_to_load: 'latest'
        label_types_to_model:
          - 'primary'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'primary'
  ###########################################
  # PANTHERA (TESTING) ################
  ###########################################
  panthera:
    paths:
      master_tfr: 'master.tfrecord'
      inventory: 'inventory_list.csv'
    experiments:
      empty_vehicle_species:
        model: ResNet18
        label_types_to_model:
          - 'primary'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'primary'
      species:
        model: ResNet18
        label_types_to_model:
          - 'primary'
