general:
  debug: False
  logging: debug
  logging_to_disk: True
  number_of_gpus: 1
  # number of cpus used for image pre-processing (use all if possible)
  number_of_cpus: 4
  # number of images buffered in image pre-processing
  # (increase if GPU utilization is below 90%)
  buffer_size: 10192
  # batch is is split to all GPUs - has to be divisible by number of GPUs
  batch_size: 32
  max_number_of_epochs: 70
  save_sample_images_to_disk: False

run:
  location: southern_africa
  experiment: species
  identifier_postfix: '_inceptionresnetv2'
   # location: west_africa
   # experiment: species
   # add postfix to run directory: run_YYYYMMDD + postfix
   # identifier_postfix: ''
  # location: cats_and_dogs
  # experiment: cats_vs_dogs
  # identifier_postfix: ''

paths:
  root: '/host/data_hdd/'
  experiments: 'experiments/'
  models: 'models/'

paths_debug:
  root: 'D:\\Studium_GD\\Zooniverse\\Data\\camtrap_trainer\\data\\'
  experiments: 'experiments\\'
  models: 'models\\'

locations:
  southern_africa:
    experiment_id: 'ts'
    image_save_side_max: 500
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
    paths:
      master_tfr: 'master.tfrecord'
      #inventory: 'D:\Studium_GD\Zooniverse\CamCatProject\data\inventory_list.csv'
      inventory: 'inventory_list.csv'
    training_splits:
      train: 0.9
      validation: 0.05
      test: 0.05
    experiments:
      empty_vehicle_species:
        model: ResNet18
        labels_project: panthera
        labels_version: empty
        label_types_to_model:
          - 'species'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'species'
      species:
        model: InceptionResNetV2
        labels_project: panthera
        labels_version: species
        label_types_to_model:
          - 'species'
        balanced_sampling_min: False
        balanced_sampling_label_type: 'species'
  west_africa:
    experiment_id: 'ts'
    image_save_side_max: 500
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
    paths:
      master_tfr: 'master.tfrecord'
      #inventory: 'D:\Studium_GD\Zooniverse\CamCatProject\data\inventory_list.csv'
      inventory: 'inventory_list.csv'
    training_splits:
      train: 0.9
      validation: 0.05
      test: 0.05
    experiments:
      empty_vehicle_species:
        model: ResNet18
        labels_project: panthera
        labels_version: empty
        label_types_to_model:
          - 'species'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'species'
      species:
        model: ResNet18
        labels_project: panthera
        labels_version: species
        label_types_to_model:
          - 'species'
        balanced_sampling_min: False
        balanced_sampling_label_type: 'species'
  cats_and_dogs:
    experiment_id: 'ts'
    image_save_side_max: 200
    image_processing:
      output_height: 150
      output_width: 150
      resize_side_min: 150
      resize_side_max: 165
      color_manipulations: True
    paths:
      master_tfr: 'master.tfrecord'
      inventory: 'inventory_list.csv'
      images: "D:\\Studium_GD\\Zooniverse\\Data\\transfer_learning_project\\images\\4715\\all"
    training_splits:
      train: 0.9
      validation: 0.05
      test: 0.05
    experiments:
      cats_vs_dogs:
        model: cats_vs_dogs
        labels_project: cats_vs_dogs
        labels_version: cats_vs_dogs
        label_types_to_model:
          - 'primary'
        balanced_sampling_min: True
        balanced_sampling_label_type: 'primary'
        initialize_weights: False
        initialize_cfg:
          model_dir: "cats_and_dogs\\experiments\\cats_vs_dogs\\run_201803300903\\"
          model_name: 'latest'
          replace_last_layer: False
          starting_epoch_zero: False
